spring.application.name=encuentralo

# Configuración de la conexión de datos (DataSource)
spring.datasource.url=jdbc:mysql://localhost:5555/Encuentralo?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Custom env variables
yelp.api.key=${YELP_API_KEY:MISSING_KEY}
yelp.locale=${YELP_LOCALE:es_ES}

mock.json=true
max.results=${MAX_RESULTS:20}
server.timezone=${SERVER_TIMEZONE:Europe/Madrid}
