spring.application.name=encuentralo

# Configuración de la conexión de datos (DataSource)
spring.datasource.url=jdbc:mysql://localhost:3306/encuentralo_db?serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Custom env variables
yelp.api.key=${YELP_API_KEY}

